### ISSUE TITLE
Fix the current highlighter of the current section 

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [mostuselessboy/web3xai#1]
It has been oberserved that while moving to the tab such as about, highlights or docs. The current highlighter is not shown. Means that while in the section of 'about', about section is not highlighted. 

Below picture shows that even in the about section, home header is still hihglighted. 

![image](https://github.com/mostuselessboy/web3xai/assets/68806440/2a1c91bd-435c-4d05-97bd-05037e081fa6)

**Comment by mostuselessboy** [comment]
![image](https://github.com/mostuselessboy/web3xai/assets/85026406/928c4b3a-f4ac-4c22-bcd1-51d4cd38be23)
Thanks for the putting this issue. Your issue has been resolved.
