### ISSUE TITLE
Favicon is missing for the Web3xAI 

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [mostuselessboy/web3xai#2]
![image](https://github.com/mostuselessboy/web3xai/assets/68806440/322a4599-0cf5-4008-af5b-cb06c43a57d4)

**Comment by mostuselessboy** [comment]
![image](https://github.com/mostuselessboy/web3xai/assets/85026406/788d6c00-5a0f-41e2-be5c-42612f8a47a0)
Thank for identifying the problem, we have fixed your issue
